name: Deploy Frontend - Multi-Stage (dev, qa, prod)

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            ENV_NAME=${{ github.ref_name }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/<your-ecr-repo-name>:${{ github.ref_name }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/frontend

            echo "Pulling latest image..."
            docker pull ${{ steps.login-ecr.outputs.registry }}/<your-ecr-repo-name>:${{ github.ref_name }}

            echo "Stopping existing container if any..."
            docker-compose -f docker-compose.yml stop frontend-${{ github.ref_name }}
            docker-compose -f docker-compose.yml rm -f frontend-${{ github.ref_name }}

            echo "Deploying new version..."
            docker-compose -f docker-compose.yml up -d frontend-${{ github.ref_name }}
